# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, filepath, network }:

cabal.mkDerivation (self: {
  pname = "spacecookie";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ filepath network ];
  meta = {
    description = "gopher server daemon";
    license = self.stdenv.lib.licenses.gpl3;
    platforms = self.ghc.meta.platforms;
  };
})
